// File: GlobalUsings.cs
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using System;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using PetitionD.Infrastructure.Network;
global using PetitionD.Infrastructure.Network.Sessions;
global using PetitionD.Infrastructure.Network.Packets;
global using PetitionD.Core.Models;
global using PetitionD.Core.Interfaces;
global using PetitionD.Infrastructure.Database;
global using PetitionD.Services;
global using NC.PetitionLib;
global using NC.ToolNet.Networking.Protocol;